// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "user_api/internal/handler/user"
	"user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: user.SetUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user/v1"),
	)
}
