// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "gozero_study/internal/handler/message"
	user "gozero_study/internal/handler/user"
	"gozero_study/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: user.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: user.SetUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/user/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.MessageMiddleWare},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/from/:name",
					Handler: message.Gozero_studyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/ping",
					Handler: message.PingHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/message/v1"),
	)
}
